substitutions:
  _IMAGE: us-central1-docker.pkg.dev/raven-ai-6ff76/raven-api/obroh-backend:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
